### ISSUE TITLE
Skip scenarios

### ISSUE THREAD

**Issue by fccoelho7** [TheBrainFamily/cypress-cucumber-preprocessor#51] opened 2018-05-30 13:25 UTC
Does have any way to skip some scenarios by adding a tag `@skip` for example or another approach?

**Comment by lgandecki** [comment] 2018-06-04 09:00
Not currently, there is #46 that implements this, would you like to take a look and review? It would be great to have another pair of eyes on it

**Comment by lgandecki** [comment] 2018-07-14 06:18
Duplicate of #24, should come soon when #46 / #58 gets merged in. I'm closing this one out to clean things up a bit - please observe #24 issue or the #58 PR

Thanks!

**Closed by lgandecki** 2018-07-14 06:18 UTC
