### ISSUE TITLE
Scenario outlines not pulling variable from examples

### ISSUE THREAD

**Issue by breeny** [TheBrainFamily/cypress-cucumber-preprocessor#47] opened 2018-04-29 12:43 UTC
In a test scenario I have written, I am trying to pull a variable from the examples table and have it in the test name, however it seems to not parse the variable from the feature file. In my case, I have a field called name that I am trying to use. I have tried it both as `<name>` and `"<name>"`.

![image](https://user-images.githubusercontent.com/2724571/39406715-97c2ead6-4bfe-11e8-94e0-c9172f77e053.png)

![image](https://user-images.githubusercontent.com/2724571/39406719-a0d73d16-4bfe-11e8-82cb-b7a83de5b48b.png)

![image](https://user-images.githubusercontent.com/2724571/39406727-a5bd2926-4bfe-11e8-9791-0eea63460258.png)

Is this expected behaviour or a bug?

**Comment by lgandecki** [comment] 2018-04-30 03:47
I’ve never seen this work like that for the names of the scenarios. Could you verify the bevior with pure cucumberjs? It should be very easy - you have the feature file already, and your step definitions are almost copy paste (capitalize Given/when/then in the cucumberjs version and import them)

**Comment by lgandecki** [comment] 2018-05-23 11:08
@7etrahedral looks like he wants to use the variable in the Scenario Outline: line, of which I don't seen an example in your link :-)

I hope that what's in the link works, we do have some tests for it :  https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/integration/ScenarioOutline.feature

**Comment by 7etrahedral** [comment] 2018-05-23 11:18
ah, I see..
mybad..
in that case, I also never see that kind of syntax before, since it should be create another scenario.

Thanks @lgandecki

**Comment by lgandecki** [comment] 2018-07-14 07:39
@breeny could you take a look at that feature file I pointed to above, and tell me if what you are talking about is the wrong display in the report or a missing functionality?

**Comment by Sjain01** [comment] 2018-08-08 11:16
@lgandecki - I also face this same issue , is there any solution for it. The issue is with displaying the values used within examples on Scenario outline.

**Comment by novascreen** [comment] 2018-09-12 22:42
would be great to have this reflect the value being used, if you could point out where that might be fixed I could do a PR

**Comment by holgergp** [comment] 2019-03-01 11:15
This should work by now as #137 was merged.
At least my usecase at https://github.com/holgergp/cypressioCucumberExample works now with this change.
Could you try it with version 1.11.0 of the preprocessor?

**Comment by lgandecki** [comment] 2019-09-25 08:40
I'll assume this is fixed and close. If the problem still persists please comment here and tag me or create a new issue. Thanks!

**Closed by lgandecki** 2019-09-25 08:40 UTC

**Comment by DanielStoica85** [comment] 2019-11-27 15:50
Hey guys,

I am not sure if this should actually be fixed by now, but I just encountered the same issue:

![image](https://user-images.githubusercontent.com/16979375/69738235-09e30300-1136-11ea-9801-e666f5023168.png)

**Comment by lgandecki** [comment] 2019-11-27 16:59
could you show us your .feature file?

**Comment by DanielStoica85** [comment] 2019-11-28 09:36
Yes.

`Feature: Main Navigation

  As a logged in user
  I want to navigate between pages by using the main menu

  Background: Login
    Given I am logged in

  Scenario Outline: Navigating between main pages
    When I click on "<icon>" icon from main navigation
    Then I should get redirected to "<page>" Page

    Examples:
      | icon                  | page        |
      | svg.fa-sitemap        | /assets/map |
      | svg.fa-tachometer-alt | /dashboard  |
      | svg.fa-analytics      | /alerts     |
      | svg.fa-cogs           | /settings   |`

**Comment by holgergp** [comment] 2019-11-28 10:33
I'll have look at it later. 
It worked for me in this repo: https://github.com/holgergp/cypressioCucumberExample (features in german language though :( )
I'll check if there has been a regression. Which versions of cypress and the cucumber-preprocessor  are you using?

**Comment by holgergp** [comment] 2019-11-28 12:44
I bumped versions in my example at  https://github.com/holgergp/cypressioCucumberExample. Variable pulling seems to work there (https://travis-ci.org/holgergp/cypressioCucumberExample/builds/618177079). 
Please check this feature: https://github.com/holgergp/cypressioCucumberExample/blob/master/cypress/integration/beans.feature
Maybe you are using an older version of the preprocessor?

**Comment by DanielStoica85** [comment] 2019-11-28 17:38
I don't think that's the case. Cypress version is 3.6.0 and preprocessor version is 1.16.2

**Comment by holgergp** [comment] 2019-11-29 10:44
Maybe then I just don't get the erroneous output you provided. Sorry for that.
Which outputs are you expecting?
As the tests pass I assume that the variables get substituted correctly in the test steps. 
The OP wanted to see an example variable substituted in each scenario outline run (as a part of the scenario outline). In your feature file I don't see a variable substitution in the scenario outline definition.
Does this work as expected?
`  Scenario Outline: Navigating between main pages to <page>
`
