### ISSUE TITLE
 Cypress Error: Step implementation missing for: I open mortgage calculator page

### ISSUE THREAD

**Issue by Olubolar614** [TheBrainFamily/cypress-cucumber-preprocessor#379] opened 2020-05-21 19:39 UTC
I'm currently trying to implement cypress e2e tests for a basic mortgage calculator using bdd style. My feature file location is  cypress/integration/mortgage.feature and my step file is at cypress/integration/mortgage/mortgage.js Would appreciate if anyone could help.

Editor - VS Code

I'm getting this error "error: Step implementation missing for:" whenever I run the tests.                                                               
 Please find below error logs. I will appreciate if anyone could help.

Error  Step implementation missing for: I open basic mortgage calculator page  View stack trace Error: Step implementation missing for: I open basic mortgage calculator page
• at Context.resolveAndRunStepDefinition (https://react-redux.realworld.io/__cypress/tests?p=cypress/integration/mortgage.feature-207:24485:11)
• at Context. (https://react-redux.realworld.io/__cypress/tests?p=cypress/integration/mortgage.feature-207:23851:35)
• From previous event:
• at Context.thenFn (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:132380:26)
• at Context.then (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:132819:21)
• at Context. (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144927:21)
• at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144402:33
• From previous event:
• at runCommand (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144381:14)
• at next (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144524:14)
• at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144552:16
• From previous event:
• at next (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144524:34)
• From previous event:
• at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144565:37
• From previous event:
• at run (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144558:19)
• at Object.cy. [as then] (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144970:11)
• at Context.runnable.fn (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:145202:24)
• at callFn (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88335:21)
• at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88322:7)
• at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:149207:28
• From previous event:
• at Object.onRunnableRun (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:149195:20)
• at $Cypress.action (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:141473:61)
• at Test.Runnable.run (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:148003:13)
• at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88994:10)
• at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:89120:12
• at next (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88903:14)
• at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88913:7
• at next (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88815:14)
• at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88876:7
• at next (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:149131:16)
• at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:149152:11
• From previous event:
• at onNext (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:149149:57)
• at done (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88275:5)
• at callFn (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88358:7)
• at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88322:7)
• at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:149207:28
• From previous event:
• at Object.onRunnableRun (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:149195:20)
• at $Cypress.action (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:141473:61)
• at Hook.Runnable.run (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:148003:13)
• at next (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88837:10)
• at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88881:5
• at timeslice (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:82807:27) 

### Feature file ####
Feature: Ultimate Mortgage Calculator Basic Mortgage Calculator successful submit

Scenario: Check if Ultimate Mortgage Calculator Basic Mortgage Calculator returns successful messages

  Given I open basic mortgage calculator page
  When I enter the values for amount and term
   |amount|term|
   |250000| 27 |
   |300000| 28 |

  And I enter the values for interest rate and mortgage fees
   |rate  | fee  |
   |1.41  | 1198 |
   |1.60  | 2500 |
  Then I submit the form

#### Step definitions file code ####

import {Given, When, Then} from "cypress-cucumber-preprocessor/steps"

Given('Given I open basic mortgage calculator page', () => {

cy.visit('https://www.moneysavingexpert.com/mortgages/mortgage-rate-calculator/')
});

When('I enter the value for mortgage debt', datatable => {

datatable.hashes().forEach [element => {
    cy.get('#amount').clear(element.amount) 
    cy.get('#amount').type(element.amount)
    cy.get('#term').clear(element.term) 
    cy.get('#term').type(element.term)
    
}]

When('I enter the values for interest rate and mortgage fees', datatable => {

       datatable.hashes().forEach[element => {
        cy.get('#rate').clear(element.rate) 
        cy.get('#rate').type(element.rate)
        cy.get('#fees-value').clear(element.fee) 
        cy.get('#fees-value').type(element.fee)
        
    }];

Then('I submit the form')
    cy.get('.btn--default').click()

  })
})

###  Package JSON ####
{
"name": "cypressger",
"version": "1.0.0",
"description": "mortgage cypress test",
"main": "index.js",
"scripts": {
"test": "test"
},
"author": "oluseun",
"license": "ISC",
"devDependencies": {
"cypress": "^4.5.0"
},

"cypress-cucumber-preprocessor": {
"nonGlobalStepDefinitions": true
}

}

**Comment by lgandecki** [comment] 2020-05-22 08:12
Hello, please create a simple reproduction and push to github. To be honest that should be easier not only for us - but also for you, no need to copy and paste files to a text input :) Also from what you pasted we can't see what's the folder structure and it is crucial for the plugin to work properly.

**Comment by Olubolar614** [comment] 2020-05-22 13:31
Hi Lukasz,

Thanks for the quick response. I will try to push the simple reproduction
to github.

Kind regards

Olu

**Comment by Olubolar614** [comment] 2020-05-22 21:38
Hi Lukasz,

Please find below link to the simple reproduction github repository. I look
forward to your feedback.

Link - https://github.com/Olubolar614/olusimpletests

Kind regards

Olu

**Comment by dane-harnett** [comment] 2020-05-23 04:25
The problem is that you have `Given` inside the step definition...

```
Given('Given I open basic mortgage calculator page', () => {
```

Needs to change to:

```
Given('I open basic mortgage calculator page', () => {
```

**Comment by Olubolar614** [comment] 2020-05-23 06:17
Hi Dane,

Thanks for spotting the school boy error from my side. I would appreciate
if you can help to resolve this new issue relating
to clicking the form button. Then function "I submit the form" is throwing
up error and I have also committed my latest
code  in github . I look forward to hearing from you.

Link - https://github.com/Olubolar614/olusimpletests

Kind regards

Olu

**Comment by lgandecki** [comment] 2020-05-23 07:04
Thanks for helping out @dane-harnett . 
This doesn't seem like a plugin issue so Im going to close it.

**Closed by lgandecki** 2020-05-23 07:04 UTC

**Comment by Olubolar614** [comment] 2020-05-23 07:13
Hi Lukasz,

I agree, it is not a plugin issue, but my tests are still failing around
clicking the submit form button. I would appreciate, if someone can
help although you have already closed the issue ticket.

Kind regards

Olu

**Comment by Olubolar614** [comment] 2020-06-05 07:09
Hi  Lukasz,

I am currently getting a new error whenever I run a cypress test in my
local environment. Test execution in
my local environment has been smooth (passing) for the past 2 weeks but
this error started occurring yesterday.

Error message - The plugins file is missing or invalid
Repo link - https://github.com/Olubolar614/olusimpletests

I look forward to hearing from you.

Kind regards

Oluseun

**Comment by badeball** [comment] 2020-06-05 08:42
Hi, @Olubolar614, your directory structure is wrong. Both the `plugin` and the `integration` directory should be inside a directory named `cypress`.
