### ISSUE TITLE
The step definitions are not detected from package.json

### ISSUE THREAD

**Issue by prsdcse** [TheBrainFamily/cypress-cucumber-preprocessor#89] opened 2018-08-23 10:30 UTC
I have done all the configuration mentioned in the readme.

in plugin/index.js
`const cucumber = require('cypress-cucumber-preprocessor').default;
module.exports = (on, config) => {
  on('file:preprocessor', cucumber());
};`

in package.json
`"cypress-cucumber-preprocessor": {
    "step_definitions": "./cypress/support/step_definitions"
  }`

When i run the test i see this error. 

> Error: Step implementation missing for: Goto google page

>

**Comment by lgandecki** [comment] 2018-08-24 14:47
Thanks for reporting..
Although I think we will need a repro here, as you can see this repository actually uses the plugin to test itself, so we know it works - at least in the most basic way. :-)

Two things:

a) Are you on windows?
b) Can you try "cypress/support/..." instead of "./cypress/support/..."?

**Comment by lgandecki** [comment] 2018-08-29 06:16
Closing this because there is no way to reproduce, and this is basic functionality. 
Please reopen with a repro/after answering the a/b points above. 

Thanks!

**Closed by lgandecki** 2018-08-29 06:16 UTC

**Comment by avikhazra** [comment] 2019-09-15 12:32
I m using cypress/support/... in windows 10 and same problem faced. same config I am also using. the same issue faced
@lgandecki please help me on this

**Comment by gero0413** [comment] 2019-11-13 19:46
Yo también estoy presentando el mismo problema
