### ISSUE TITLE
Issue running tagged tests with cypress-tags

### ISSUE THREAD

**Issue by davidzambrana** [TheBrainFamily/cypress-cucumber-preprocessor#274] opened 2019-11-20 11:33 UTC
## Description

I am testing the `cypress-tags run -e TAGS='not @foo and (@bar or @zap)'` feature in my project but I've found a problem when trying it out.

When I run `cypress-tags run -e TAGS='@login'` it works as expected, running only the scenarios tagged as `login` but when trying the opposite `cypress-tags run -e TAGS='not @login'` I get this errors:
```
$ cypress-tags run -e TAGS='not @login'
Error parsing tags: 'not'. Message: empty stack
Error parsing tags: 'not'. Message: empty stack
Error parsing tags: 'not'. Message: empty stack
Error parsing tags: 'not'. Message: empty stack
Error parsing tags: 'not'. Message: empty stack
Error parsing tags: 'not'. Message: empty stack
Error parsing tags: 'not'. Message: empty stack
Error parsing tags: 'not'. Message: empty stack
Error parsing tags: 'not'. Message: empty stack
Error parsing tags: 'not'. Message: empty stack
```
So what it does is it tries to run all the scenarios but since not one matches the criteria all of them are set to passed without running them.

My versions are:
```
"cypress-cucumber-preprocessor": "^1.16.2"
"cypress": "3.6.1"
```
Ubuntu 18.04.3 LTS

**Comment by lgandecki** [comment] 2019-11-28 09:11
would you be able to create a simple demonstration/reproduction? Maybe based on a fork of one of our example repos? That will increase the chance that one of us will find the time to investigate and fix :) 

Thanks!

**Comment by davidzambrana** [comment] 2019-11-28 17:14
When trying to create the reproducible version for you to try, I've seen that it was because I have more than one command in my npm script:

`"test:bug": "secrets-env-script cypress-tags run -e TAGS='not @login'"`

`secrets-env-script` is a script used to read some private data right before running cypress-tags. Removing that or even setting `&&` in between the two commands caused the feature to work well.

With that info, let me know if you want me to close this issues or you'd like to get deeper on that.

Thanks

**Comment by davidzambrana** [comment] 2019-12-11 14:47
Hi @lgandecki,

I was able to create a reproduction of the error, you can find it here: https://github.com/davidzambrana/test-cypress

Just install the dependencies with `npm` or `yarn` and see the error running `yarn test:error`

The only difference that makes it to fail is running another command right beforehand. As I commented I can avoid the error by setting `&&` between the commands, but that arose a different problem on my setup. 

Let me know if I can help with anything else.

**Comment by vibhasomashekhara** [comment] 2020-10-23 10:43
I have similar issues with "cypress-cucumber-preprocessor": "^4.0.0",
I have pre and post steps in my scripts and the tests marked with @ignore are not actually ignored. They are shown as skipped in test results. I was using v1.19.0 of cypress-cucumber-preprocessor before and it all worked like a charm.

    "pretest:ci": "rm -fr report",
    "test:ci": "NO_COLOR=1 cypress run --spec \"cypress/integration/tests/**/*.feature\"  -e TAGS='not @ignore and not @wip'",
    "posttest:ci": "node cypress/plugins/reporter.js",

**Comment by sandra-ouadghiri** [comment] 2021-04-20 15:28
I have the same issue
-  npx cypress-tags run -e TAGS="@setup"   OK (1 scenario found & executed)
-  npx cypress-tags run -e TAGS="not @setup"    KO (Error parsing tags: 'not'. Message: empty stack)
-  Funny thing is, if I put that as ENV variables in cypress.json (like 'not @ignored' is documented) then it works. So it's solely when through CLI.

I got the same results in powershell, cmd and git bash (so it is not powershell interpreting issue or something like that).
And it's not 'No matching tags found' so there's definitively a bug behing that.

Once fixed, I guess an additional test for the framework should be added so that this doesn't regress again.

"cypress": "^6.5.0",
"cypress-cucumber-preprocessor": "^4.0.0",

**Comment by badeball** [comment] 2021-04-20 15:57
> They are shown as pending in test results. 

"Pending" is how skipped tests are shown in the results.

https://glebbahmutov.com/blog/cypress-test-statuses/

**Comment by badeball** [comment] 2021-04-20 15:59
@davidzambrana, your script `yarn test:error` would work if you quoted correctly, a

```
{
  "test:error": "./scripts/run-local-task.sh cypress-tags run -e TAGS=\\'not @skip\\'"
}
```

.. alternatively, you can replace `eval` with `exec` and leave the quoting as is. You probably don't want a subshell to begin with anyway.
```

**Comment by badeball** [comment] 2021-04-20 16:00
@sandra-ouadghiri, your problem is certainly related to argument interpretation and has likely nothing to do with the preprocessor. You're example, `npx cypress-tags run -e TAGS="not @setup"`, works totally fine in bash.

**Comment by badeball** [comment] 2021-04-20 18:58
Closing, as this likely doesn't pertain preprocessing at all. I realize that escaping quotes and knowing when to do it can seem daunting at first, and it is, especially when you're propagating arguments between multiple layers of abstraction. The clue here is to familiarize yourself with exactly what is being propagated throughout and verifying it. It's also a type of issue you're likely going to keep encountering in the future no matter what tools you use.

However, this isn't an issue with the processor. The preprocessor can only process what it is handed and in all your cases it has been handed `"not"`, which isn't a valid tag filter, and this is due to some error in argument interpretation in _your environment_.

If you run eg. `cypress open -e TAGS="foo bar"`, go to "settings", expand "configuration" and expand "env", you can observe what Cypress actually resolves for you. You should hopefully see `TAGS: "foo bar"` in that case.

**Closed by badeball** 2021-04-20 18:58 UTC

**Comment by rkadhane** [comment] 2022-02-18 12:39
I faced similar issue

**Comment by myrk2022** [comment] 2022-02-18 12:49
I have faced similar issue. Resolved it by removing quotes around tag in the script in package.json eg @smoke instead of '@smoke'

should work 
{ 
 "test:error": "./scripts/run-local-task.sh cypress-tags run -e TAGS=@skip" 
}
