### ISSUE TITLE
Using import and export inside step definitions

### ISSUE THREAD

**Issue by bensampaio** [TheBrainFamily/cypress-cucumber-preprocessor#52] opened 2018-05-31 08:48 UTC
I am trying to use `import` and `export` inside step definitions but it constantly says that `sourceType: "module" is required`. I tried using `require` but then it still gives the same error since the required modules use `import` and `export` anyway. Is there a workaround for this? Thank you!

**Comment by lgandecki** [comment] 2018-06-04 14:19
Hello. Is there a reason why you can't just use require in your tests? What are you importing?  
could you make a repro? 

We could possibly try to somehow rewrite imports to require internally but it is a few hours of work, at least :) As always - would love to take a PR!

**Comment by bensampaio** [comment] 2018-06-04 15:54
Well to give a very simple example we have a module with constants for HTTP methods like:

```
export const GET = 'GET';
export const POST = 'POST';
```

We want to make sure these constants are used all across JS files but we cannot `import` or `require` them in step definition files because `export` seems to not be allowed. However, `import` and `export` can be used in all other kinds of cypress files so I don't get the difference here. We are using the webpack preprocessor btw.

At the moment I cannot contribute with a PR but maybe that will change in the future. For now I would at least like to understand what the problem is. And in the meantime will keep writing cypress tests without this preprocessor.

**Comment by lgandecki** [comment] 2018-06-04 16:07
To have cypress work with .feature files what we do here is we "transpile" them into .js. Our code reads the feature file and based on it creates a js file (one per .feature), and that's what cypress gets to execute. The problem is - since it's all in one file, and import/export has to be at the top - it doesn't work out of the box. 

take a look here: 
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/index.js#L15

**Comment by bensampaio** [comment] 2018-07-10 20:57
Why not generate a `.js` file out of the `.feature` file that imports the step definitions used in that file instead? The import statements would then be resolved by another preprocessor. This is just an idea, not sure if it would fit all the use cases, but it would reduce a lot of confusion.

**Comment by lgandecki** [comment] 2018-07-13 07:55
Not sure why not :-) I don't remember whether that crossed my mind when I initially was trying to hack this together.
It sounds like a reasonable idea though... I will give it a shot and see if this is something that could work. 
Tha

**Comment by lgandecki** [comment] 2018-07-13 08:45
Fixed in 1.2.0  / #72 ! 
Thanks so much :) this was spot on. 
I think I should be able to get TypeScript to work now as well.. Let's see.

**Closed by lgandecki** 2018-07-13 08:45 UTC

**Comment by bensampaio** [comment] 2018-07-13 15:30
Wow that was fast! Looking forward to give it a try when I'm back from holidays :D Thanks!

**Comment by LeroyDoornebal** [comment] 2019-04-02 12:59
@lgandecki Did you ever get typescript to work as well? At the moment, when I try to import a .ts file like so:
```
import { testHooks } from 'src/testing/testHook';
```

The module can not be resolved, although my editor can find the file (thus ruling out a wrong file reference)

**Comment by LeroyDoornebal** [comment] 2019-04-02 17:19
@lgandecki Did you manage to get it to work with TypeScript? I've been trying to import a .ts file in the step_definitions (just a simple object with values), but for some reason it is unable to locate the module. I'd like to import something from the `src` directory (outside of the cypress directory). I am not really sure what is going on here and if this could be fixed using just webpack config.

testIds.ts
```
export const testHooks = {
  LookupToggleButton: 'lookup-toggle-button',
  LookupSearchByTextField: 'lookup-search-by-text--search-field',
  LookupSearchByTextClearIcon: 'lookup-search-by-text--clear-icon',
  CustomerCard: 'customer-card'
};
```

step definitions file 
```
import { Given, Then, When } from 'cypress-cucumber-preprocessor/steps';
import { testIds } from 'src/testing/testIds';

Given('I navigate to the Feedback Loop application', () => {
  cy.visit('http://localhost:3000/#/integrations/ipccc/0/2/0');
});
```

webpack.config.json
```
module.exports = {
  resolve: {
    extensions: ['.ts', '.js']
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: [/node_modules/],
        use: [
          {
            loader: 'ts-loader'
          }
        ]
      },
      {
        test: /\.feature$/,
        use: [
          {
            loader: 'cypress-cucumber-preprocessor/loader'
          }
        ]
      }
    ]
  }
};
```

The error I get:
```

	•	1000 x 660 (100%)
./cypress/support/step_definitions/lookup/featureFile
Module not found: Error: Can't resolve 'src/testing/test' in '/Users/user/Development/project/cypress/support/step_definitions/lookup'
resolve 'src/testing/testIds' in '/Users/user/Development/project/cypress/support/step_definitions/lookup'
  Parsed request is a module
  using description file: /Users/user/Development/project/package.json (relative path: ./cypress/support/step_definitions/lookup)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/user/Development/project/cypress/support/step_definitions/lookup/node_modules doesn't exist or is not a directory
      /Users/user/Development/project/cypress/support/step_definitions/node_modules doesn't exist or is not a directory
      /Users/user/Development/project/cypress/support/node_modules doesn't exist or is not a directory
      /Users/user/Development/project/cypress/node_modules doesn't exist or is not a directory
      /Users/user/Development/node_modules doesn't exist or is not a directory
      /Users/user/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/user/Development/projectnode_modules
        using description file: /Users/user/Development/project/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /Users/user/Development/project/package.json (relative path: ./node_modules/src/testing/testIds)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/user/Development/projectnode_modules/src/testing/testIds doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/user/Development/projectnode_modules/src/testing/testIds.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/user/Development/projectnode_modules/src/testing/testIds.js doesn't exist
            as directory
              /Users/user/Development/projectnode_modules/src/testing/testIds doesn't exist
[/Users/user/Development/project/cypress/support/step_definitions/lookup/node_modules]
[/Users/user/Development/project/cypress/support/step_definitions/node_modules]
[/Users/user/Development/project/cypress/support/node_modules]
[/Users/user/Development/project/cypress/node_modules]
[/Users/user/Development/node_modules]
[/Users/user/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/user/Development/projectnode_modules/src/testing/testIds]
[/Users/user/Development/projectnode_modules/src/testing/testIds.ts]
[/Users/user/Development/projectnode_modules/src/testing/testIds.js]
 @ ./cypress/support/step_definitions/lookup/featureFile 2:0-49 3:12-21
 @ ./cypress/integration/lookup/featureFile.feature
```

**Comment by LeroyDoornebal** [comment] 2019-04-02 18:25
Ah. It was an issue with the webpack.config.js. I had to change my webpack config accordingly. I'll post it here for completeness, maybe others can benefit from it too.

```javascript
const path = require('path');
const paths = require('../config/paths');
// paths.appPath = '.'

module.exports = {
  resolve: {
    extensions: ['.ts', '.js', '.feature'],
    modules: [path.resolve(paths.appPath), 'node_modules']
  },
  module: {
    rules: [
      {
        test: /\.feature$/,
        use: [
          {
            loader: 'cypress-cucumber-preprocessor/loader'
          }
        ]
      },
      {
        test: /\.ts$/,
        exclude: [/node_modules/],
        use: [
          {
            loader: 'ts-loader'
          }
        ]
      }
    ]
  }
};

```
