### ISSUE TITLE
How to use tags within feature files and create @RunWith for it?

### ISSUE THREAD

**Issue by aneesforgit** [TheBrainFamily/cypress-cucumber-preprocessor#48] opened 2018-05-17 05:58 UTC
Hi,

I am trying to use tags like @smoke and @regression within features to create suites for my tests. Is there any way we can do this and run suites within runner class as we do with other cucumber tests?

**Comment by lgandecki** [comment] 2018-07-14 06:18
Duplicate of #24, should come soon when #46 / #58 gets merged in. I'm closing this one out to clean things up a bit - please observe #24 issue or the #58 PR

Thanks!

**Closed by lgandecki** 2018-07-14 06:18 UTC
