### ISSUE TITLE
Unable to stub http requests

### ISSUE THREAD

**Issue by simbro** [TheBrainFamily/cypress-cucumber-preprocessor#154] opened 2019-04-02 10:41 UTC
When I try to run cy.server() in order to mock http requests that are executed as part of the tests, I get the following error:

`Uncaught CypressError: Cannot call "cy.server()" outside a running test.....`

I don't know how to get this to work.  This is my code:

    import { Given, Then } from 'cypress-cucumber-preprocessor/steps'

    beforeEach(() => {
      cy.server()

      cy.route({
        method: 'GET',
        url: '/',
        response: []
      })
    })

    const url = 'http://localhost:8080'

    Given('I click the big button', () => {
      cy.visit(url)
      cy.get('.btn').click()
    })

    Then('I can get the MOTD', (title) => {
      cy.title().should('include', title)
    })

**Comment by lgandecki** [comment] 2019-04-02 13:51
Can you try this in cypress itself and see if you can get it to work there? beforeEach is straight from cypress - so if it doesn't work there, it won't work anywhere and the problem is not related to our tool.

You might also want to try Background section

**Comment by lgandecki** [comment] 2019-05-14 06:05
Closing it for now until you can give us more information

**Closed by lgandecki** 2019-05-14 06:05 UTC
