### ISSUE TITLE
Unable to run Scenario Outline Examples using tags

### ISSUE THREAD

**Issue by phpworker** [TheBrainFamily/cypress-cucumber-preprocessor#489] opened 2020-12-23 07:03 UTC
### Current behavior

Hello Everyone!
Maybe this is more a question, but couldn't also find any examples showing  that this works with cypress-cucumber-preprocessor (great work btw!). For me, this specific feature is one of the main reasons for using this plugin in our company.

Consider the following scenario outline:

```
  @tag1
  Scenario Outline: I order <product> 
    Given I open Checkout with "<product>"
    When  I fill checkout form
    And   I click submit order button
    Then  I check if I am on Success Page

  @tag2
  Examples:
    | product           | 
    | product1         | 
    | product2         |

  @tag3
  Examples:
    | product           | 
    | product3         | 

```
this will run all Examples (as expected):
`npx cypress open --env TAGS="@tag1"`

this will not run any Examples:
```
npx cypress open --env TAGS="@tag2"
npx cypress open --env TAGS="@tag3"
```

### Desired behavior

According to Cucumber Docs: 
https://cucumber.io/docs/cucumber/api/#tags
tags should also work as per Examples, so I can easily decide which Examples I want to run.

### Versions

* **Cypress version**: 6.2.0
* **Preprocessor version**: 4.0.0
* **Node version**: 13.7.0

**Comment by badeball** [comment] 2020-12-24 12:11
Duplicate of https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/196.

**Closed by badeball** 2020-12-24 12:11 UTC
