### ISSUE TITLE
Error on Linux machines

### ISSUE THREAD

**Issue by alopezsanchez** [TheBrainFamily/cypress-cucumber-preprocessor#10] opened 2018-02-12 17:20 UTC
Hello.

I'm trying to use the library, but it throws an error on my Linux machine (Ubuntu 16.04). On Mac works fine.

![screenshot](https://user-images.githubusercontent.com/15221596/36109950-469b862c-1021-11e8-9b16-13457fe2ce70.png)

**Comment by k-stasevich** [comment] 2018-02-13 10:03
@alopezsanchez , yes, same error, please owner help

**Comment by k-stasevich** [comment] 2018-02-13 10:09
Currently I am on 0.0.2  it is working fine now. Waiting for update!

**Comment by lgandecki** [comment] 2018-02-19 04:27
Looks like it's watchify erroring which is itself required by @cypress/browserify-preprocessor.. not sure if this is directly related to our package @fcurella would you have an idea is this something we should be able to fix internally, or should we look into the browserify preprocessor itself?

**Comment by fcurella** [comment] 2018-02-20 15:38
Doesn't the build on circle-ci run on linux? why is it working there?

**Comment by lgandecki** [comment] 2018-02-20 15:49
@fcurella  I imagine this is because on ci run we don’t do “watch”, so that part of code is never executed..? The watcher is somehow problematic, I think

**Comment by fcurella** [comment] 2018-02-20 15:57
we really delegate everything to `@cypress/browserify-preprocessor`, so the first thing I would try is if regular js tests work with just that.

I'll try to set up an ubuntu VM and try.

**Comment by fcurella** [comment] 2018-02-21 22:57
I have tried on a VM and I can reproduce the issue, but I can't figure out why it's happening.

We are not using `fsevents`, we are delegating all the watching to the `@cypress/browserify-preprocessor` plugin. If `@cypress/browserify-preprocessor` works, so should `cypress-cucumber-preprocessor`

**Comment by mgalindo** [comment] 2018-02-26 19:44
I am experiencing the same issue, Ubuntu 17.10

**Comment by lgandecki** [comment] 2018-02-27 12:18
Thanks for reporting! @mgalindo @k-stasevich @alopezsanchez could you guys confirm that the watch mode works properly on Linux, when NOT using this package?
Please do (I took those from the official https://github.com/cypress-io/cypress-browserify-preprocessor
 ):

```
npm install --save-dev @cypress/browserify-preprocessor
```
And put in your plugins file:

```javascript
const browserify = require('@cypress/browserify-preprocessor')
module.exports = (on) => {
  on('file:preprocessor', browserify())
}
 ```

Since none of my guys, nor @fcurella (which defacto became another author of this package :) ) use Linux for development this is a bit hard for us to debug, but we definitely want to have this supporting Linux watch mode, so no worries, we will get this done :) if 0.0.2 works for you meanwhile that's great, updating to a linux-compatible version should be seamless. 

If this works, then we will investigate internally, if not we can reach to the cypress guys

**Comment by vineetkumar1511** [comment] 2018-02-28 11:26
I am still getting the same error.

**Comment by lgandecki** [comment] 2018-02-28 11:29
@vineetkumar1511 just to confirm, do you mean you get the same error even without using our plugin, just browserify-preprocessor directly?

**Comment by vineetkumar1511** [comment] 2018-02-28 11:40
Yes I am using browserify preprocessor still i am getting the fsevent error.

**Comment by mgalindo** [comment] 2018-02-28 14:47
@lgandecki,
  I am happy to assist testing this, I am very new to cypress so I am going to need a bit more directions on how to test.
Should I use you example cucumber-preprocessor example? or something else.

**Comment by lgandecki** [comment] 2018-02-28 16:18
@mgalindo could you verify that cypress works in linux at all with the watch mode? Just install cypress in any project, start it up, and change something in the cypress/integration folder, see if it reloads.
@vineetkumar1511 thanks! the weird thing here is that apparently cypress does use this preprocessor by default.. so not sure why it would break when using explicitly.

**Comment by BenoitAverty** [comment] 2018-02-28 16:21
I can confirm that cypress does work in linux. Only when using cypress-cucumber-preprocessor and launching a feature do I see this error.

**Comment by lgandecki** [comment] 2018-02-28 16:38
@BenoitAverty only then? @vineetkumar1511 was claiming something else. Can you please do what I asked a few posts above, and try to run cypress with @cypress/browserify-preprocessor directly? without the use of this plugin?

**Comment by mgalindo** [comment] 2018-02-28 16:53
@lgandecki I just tested as you requested and it works in Linux, Ubuntu 17.10
This is what I did:
- Took one of the examples from the cypress example recipes repo https://github.com/cypress-io/cypress-example-recipes#form-interactions.  
- Installed the Browserify plugin, enabled the plugin as instructed above.
- If I change something in the spec file the test is executed again, no crashes.

**Comment by lgandecki** [comment] 2018-02-28 17:17
Thank you @mgalindo , looks like I will have to install desktop version of ubuntu in a vm to test what’s going on, because now I’m seriously confused :)

**Comment by mgalindo** [comment] 2018-02-28 17:31
@lgandecki Ok, let me know if I can be of any help.

**Comment by lucetius** [comment] 2018-03-01 01:28
try to remove `const {given} = require('cypress-cucumber-preprocessor')` `const {when} = require('cypress-cucumber-preprocessor')` `const {then} = require('cypress-cucumber-preprocessor')` requires from `cypress/support/step_definitions/*.js` files

**Comment by vineetkumar1511** [comment] 2018-03-01 06:48
Below is my basic test:- 
```
//const { given } = require("cypress-cucumber-preprocessor");

const url = "https://google.com";

it("I open Google page", () => {
    cy.visit(url);
});
```
below is my plugin file:-
```
// const cucumber = require("cypress-cucumber-preprocessor").default;
//
// module.exports = (on, config) => {
//     on("file:preprocessor", cucumber());
// };

const browserify = require("@cypress/browserify-preprocessor");

module.exports = (on) => {
    const options = {
        browserifyOptions: {
            extensions: [".js", ".ts"]
        }
    };
    on("file:preprocessor", browserify(options));
};
```
this is working example in ubuntu 16.


If I use cypress-cucumber-preprocessor then it won't work.Below is the code using cypress-cucumber-preprocessor

plugin/index.js
```
const cucumber = require("cypress-cucumber-preprocessor").default;

module.exports = (on, config) => {
    on("file:preprocessor", cucumber());
};
```
basic.test.js
```
const { given } = require("cypress-cucumber-preprocessor");

const url = "https://google.com";

given("I open Google page", () => {
  cy.visit(url);
});

```

this gives `error: Cannot find module 'fsevents' from '/home/vineet/data/Fujin/node_modules/chokidar/lib'`

@lgandecki sorry I forgot delete `given` and `then` thats why it is not working with `@cypress/browserify-preprocessor`.But as soon as i corrected my test case it is workng fine with `@cypress/browserify-preprocessor`.Could please help why it is not working with `cypress-cucumber-preprocessor`.

**Comment by lgandecki** [comment] 2018-03-01 07:01
@vineetkumar1511 I don't understand.. Did everything work after removing requiring of the given/then/when and using the globals?

@lucetius suggests that it should work if you remove them, I'm not sure. 

So basically change

```javascript

const { given } = require("cypress-cucumber-preprocessor");

const url = "https://google.com";

given("I open Google page", () => {
  cy.visit(url);
});

```
to
```javascript
const url = "https://google.com";

given("I open Google page", () => {
  cy.visit(url);
});
```

**Comment by lgandecki** [comment] 2018-03-01 07:47
Cool thanks, so this is workable :) Without code changes. I guess the requiring should not be recommended then.. I wonder why this is breaking. Very weird. 

@mgalindo @BenoitAverty @alopezsanchez @k-stasevich 

Could you guys give this a try as well? Use the globals. I will leave this open for a few days and close it if it seems to work for everyone.

Thanks @lucetius !

**Comment by BenoitAverty** [comment] 2018-03-01 08:17
I will try tomorrow, thanks for the help :)

**Comment by fcurella** [comment] 2018-03-01 15:55
@lgandecki if that's the issue, I think it's worth mentioning it in the documentation.

**Comment by mgalindo** [comment] 2018-03-01 17:17
I just tested commenting out the line below and Cypress is no longer crashing. At least my simple example works ok
//import { given } from "cypress-cucumber-preprocessor";

**Comment by BenoitAverty** [comment] 2018-03-02 08:02
Same behavior for me. Commenting the import and using globals makes it no longer crash.

**Comment by lgandecki** [comment] 2018-03-02 08:07
@BenoitAverty would you be able to test one more thing - add some kind of a js file and try to require it, I just want to confirm that the problem is when requiring the given/when/then, not with requiring anything.

Or @lucetius ? :) and if requiring a „helper” breakes, could you see whether it still breakes when not using the cucumber preprocessor but just the cypress/browserify?
We will have a full view of the situation then

And yeah I agree @fcurella , if it’s requiring the given/when/then that causes the problem (instead of requiring at all), I think i will just get rid of that patern completely

**Comment by BenoitAverty** [comment] 2018-03-02 08:17
I imported a file from the project and it worked fine. The problem seems to be only when importing given / when / then.

**Comment by lgandecki** [comment] 2018-03-02 08:26
Great thanks a lot @BenoitAverty !

**Comment by lucetius** [comment] 2018-03-02 14:30
@lgandecki I confirm that importing "helper" files works fine

**Comment by lgandecki** [comment] 2018-03-03 09:52
I updated the docs, closing the issue. Thanks, everyone! :-) 
Please let us know when you find more issues or need more features.

**Closed by lgandecki** 2018-03-03 09:52 UTC
Labels: bug, help wanted

**Comment by ironchicken** [comment] 2018-11-14 15:56
I have this problem, too, I think. Here's my set up:

`package.json`:

```
  "dependencies": {
    "cypress": "^3.1.1",
    "cypress-cucumber-preprocessor": "^1.6.0",
    "moment": "^2.22.2"
  },
  "devDependencies": {
    "eslint": "^5.9.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.11.0"
  },
  "scripts": {
    "cypress:open:test": "CYPRESS_BASE_URL='https://test.example.com/' cypress open",
```

`cypress/plugins/index.js`:

```
const cucumber = require('cypress-cucumber-preprocessor').default;

module.exports = (on, config) => {
  on('file:preprocessor', cucumber());
};
```

`cypress/support/step_definitions/navigation.js`:

```
/* global cy given */

given('I am on the "{string}" page', (pageName) => {
  cy.fixture('pages').then((pages) => {
    if (pages[pageName]) {
      cy.visit(pages[pageName]);
    } else {
      throw new Error(`Could not find a page called "${pageName}" in the pages fixture.`);
    }
  });
});
```

`cypress/integration/Homepage.feature`:

```
Feature: Home page
  As an user
  I want to be see the home page
  So I can see what's on the home page

  Background:
    Given I am on the "Home" page

  Scenario: On the Home page I should see home page stuff
    Then I should see the header image
```

I'm running this on Ubuntu 18.04 with `node` and `npm` from the Ubuntu package repository.

When I run `cypress open` and try to run my `Homepage.feature`, I get the following:

```
GET /__/ 200 91.132 ms - -
GET /__cypress/runner/cypress_runner.css 200 263.005 ms - -
GET /__cypress/runner/cypress_runner.js 200 627.767 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.6.3 200 2.708 ms - 71896
GET /__cypress/iframes/integration/Homepage.feature 200 13.065 ms - 750
GET /__cypress/tests?p=cypress/support/index.js-444 200 1108.924 ms - -
Error: Cannot find module 'fsevents' from '/home/me/src/bdd/node_modules/chokidar/lib'
    at /home/me/src/bdd/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/me/src/bdd/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/me/src/bdd/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/me/src/bdd/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/me/src/bdd/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/me/src/bdd/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at /home/me/.cache/Cypress/3.1.1/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:152:21)
GET /__cypress/tests?p=cypress/integration/Homepage.feature-262 200 4257.162 ms - 222
```

Is this the same problem? What can I do to fix it?

**Comment by ironchicken** [comment] 2018-11-14 18:13
It seems to be working correctly with Chrome 70 now. I'm not really sure what I changed. I've been working on the step definitions. Perhaps the problem was caused by broken step definitions?
