### ISSUE TITLE
Not compatible with @cypress/code-coverage

### ISSUE THREAD

**Issue by amitguptagwl** [TheBrainFamily/cypress-cucumber-preprocessor#198] opened 2019-08-04 14:18 UTC
When I add following in `cypress/plugins/index.js`

```js
module.exports = (on, config) => {
  on('task', require('@cypress/code-coverage/task'))
}
```

It gives compilation error "ParseError: Unexpected token"

**Comment by jcundill** [comment] 2019-08-09 23:02
I can't reproduce this, it works for me

<img width="693" alt="Screenshot 2019-08-09 at 23 59 01" src="https://user-images.githubusercontent.com/49795386/62813300-f3bb2380-bb01-11e9-9b0d-86dc0a611944.png">

Maybe you need to add to support as well as plugins [see](https://docs.cypress.io/guides/tooling/code-coverage.html#Install-the-plugin)

**Comment by jcundill** [comment] 2019-08-09 23:03
closing for now - please add more details, steps to reproduce, and reopen if appropriate

**Closed by jcundill** 2019-08-09 23:03 UTC

**Comment by rfftrifork** [comment] 2020-01-21 10:16
I'm running in to similar issues, a bit more context here:

```
Oops...we found an error preparing this test file:

  /home/rohdef/git/project/cypress/integration/acceptance-tests/my.feature

The error was:


/home/rohdef/git/project/cypress/integration/acceptance-tests/my.feature:1
#language: da
^
ParseError: Unexpected token

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        0                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     acceptance-tests/answer-account-query.feature                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by rfftrifork** [comment] 2020-01-21 10:30
Seems that it also happens if I create a simple feature in English:

```
/home/rohdef/git/project/cypress/integration/acceptance-tests/my.feature:1
Feature: As somebody I can do stuff
            ^
ParseError: Unexpected token

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies
```

Looks like it's somehow meddling with the parser

**Comment by rfftrifork** [comment] 2020-01-21 10:42
```json
    "cypress-cucumber-preprocessor": {
        "nonGlobalStepDefinitions": true,
        "stepDefinitions": "cypress/integration",
        "cucumberJson": {
            "generate": true,
            "outputFolder": "dist/cypress/cucumber-json",
            "filePrefix": "",
            "fileSuffix": ".cucumber"
        }
    },
    "devDependencies": {
        "cypress": "^3.8.2",
        "cypress-cucumber-preprocessor": "^2.0.1",
    }
```

the cypress and cypress-cucumber parts of my config (btw. as a side note, is there a way to get the `cypress-cucumber-preprocessor` config out of package.json?)

**Comment by rfftrifork** [comment] 2020-01-21 14:52
Aaaaaand, I need to find something solid to bang my head against :p Read and followed these instructions without thinking: https://docs.cypress.io/guides/tooling/code-coverage.html#Install-the-plugin so I ended up with:

```javascript
const cucumber = require('cypress-cucumber-preprocessor').default

module.exports = (on, config) => {
    on('file:preprocessor', cucumber())
}

module.exports = (on, config) => {
    on('task', require('@cypress/code-coverage/task'))
}
```

instead of something sensible like:

```javascript
const cucumber = require('cypress-cucumber-preprocessor').default
const coverage = require('@cypress/code-coverage/task')

module.exports = (on, config) => {
    on('file:preprocessor', cucumber())
    on('task', coverage())
}
```

in my `support/index.js`. Sorry for the noise.

**Comment by liebsterkamerad** [comment] 2020-07-24 22:32
> Aaaaaand, I need to find something solid to bang my head against :p Read and followed these instructions without thinking: https://docs.cypress.io/guides/tooling/code-coverage.html#Install-the-plugin so I ended up with:
> 
> ```js
> const cucumber = require('cypress-cucumber-preprocessor').default
> 
> module.exports = (on, config) => {
>     on('file:preprocessor', cucumber())
> }
> 
> module.exports = (on, config) => {
>     on('task', require('@cypress/code-coverage/task'))
> }
> ```
> 
> instead of something sensible like:
> 
> ```js
> const cucumber = require('cypress-cucumber-preprocessor').default
> const coverage = require('@cypress/code-coverage/task')
> 
> module.exports = (on, config) => {
>     on('file:preprocessor', cucumber())
>     on('task', coverage())
> }
> ```
> 
> in my `support/index.js`. Sorry for the noise.

Nothing to sorry about, I've just ran into the same problem and your answer was the only on the whole internet that helped me to solve this damn problem. I've ended up with the following plugins/index.js and it finally worked: 

`const cucumber = require('cypress-cucumber-preprocessor').default

module.exports = (on, config) => {
  require('@cypress/code-coverage/task')(on, config)
  on('file:preprocessor', cucumber())
  // include any other plugin code...

  // It's IMPORTANT to return the config object
  // with any changed environment variables
  return config
}`

I need to learn Javascript better :/

**Comment by edimitchel** [comment] 2020-08-07 11:56
I've tried with `require('cypress-react-unit-test/plugins/load-webpack')(on, config);` and it's doesn't work with.
Yes this import is for Unit Testing but it do all the work for adding code coverage that we need.
