### ISSUE TITLE
DataTable type

### ISSUE THREAD

**Issue by xuanvinhvu** [TheBrainFamily/cypress-cucumber-preprocessor#464] opened 2020-10-29 18:09 UTC
I would like to have type safety for dataTable.

```
Given("the user logged into to the tenant portal", (dataTable: DataTable) => {
   ...
});
```

The dataTable object seems to come from cucumber.js. I'm assuming there is no typescript definition for it?

**Comment by badeball** [comment] 2020-10-29 18:15
Duplicate of https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/463.

**Closed by badeball** 2020-10-29 18:15 UTC
