### ISSUE TITLE
vue-cli 3 configuration example

### ISSUE THREAD

**Issue by TobiG77** [TheBrainFamily/cypress-cucumber-preprocessor#102] opened 2018-10-06 00:46 UTC
Hi,

I've been looking into switching to cypress and I am currently unable to determine what is needed for a functioning setup.

I have created 2 minimal projects:

https://github.com/TobiG77/vue-cucumber-cypress, which does include the e2e-cypress plugin and https://github.com/TobiG77/vue-cucumber-vanilla-cypress without e2e-cypress.

The first issue is that it -if I read https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/index.js#L30 correctly - is undocumented that the 'step_definitions' will only be read from package.json, which is suprising, I would have expected the presence of the key in cypress.json to flow through.

But beyond that I can not determine how to get the setup functional. Eventually I always end up with the error below. I believe that this is ultimately inside cucumber, but have been unable to debug the problem.

```
  Running: home.feature...                                                                 (1 of 1)


  1) An uncaught error was detected outside of a test

  0 passing (680ms)
  1 failing

  1)  An uncaught error was detected outside of a test:
     Uncaught TypeError: Arguments to path.resolve must be strings

This error originated from your test code, not from Cypress.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at Object.exports.resolve (http://localhost:8088/__cypress/tests?p=cypress/integration/home.feature-098:56274:13)
      at Object.exports.relative (http://localhost:8088/__cypress/tests?p=cypress/integration/home.feature-098:56335:18)
      at getDefinitionLineAndUri (http://localhost:8088/__cypress/tests?p=cypress/integration/home.feature-098:22669:28)
      at buildStepDefinition (http://localhost:8088/__cypress/tests?p=cypress/integration/home.feature-098:22635:32)
      at SupportCodeLibraryBuilder.defineStep (http://localhost:8088/__cypress/tests?p=cypress/integration/home.feature-098:22818:67)
      at Object.2.cucumber (http://localhost:8088/__cypress/tests?p=cypress/integration/home.feature-098:29:1)
      at o (http://localhost:8088/__cypress/tests?p=cypress/integration/home.feature-098:1:265)
      at http://localhost:8088/__cypress/tests?p=cypress/integration/home.feature-098:1:316
      at Object.1./Users/tobiasgerschner/code/github/vue-cucumber-vanilla-cypress/cypress/support/step_definitions/shared_steps.js (http://localhost:8088/__cypress/tests?p=cypress/integration/home.feature-098:10:3)
      at o (http://localhost:8088/__cypress/tests?p=cypress/integration/home.feature-098:1:265)
      at r (http://localhost:8088/__cypress/tests?p=cypress/integration/home.feature-098:1:431)
      at http://localhost:8088/__cypress/tests?p=cypress/integration/home.feature-098:1:460

```

**Comment by lgandecki** [comment] 2018-10-06 04:59
I believe the behavior is documented.

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#configuration
```Step definition files are by default in: cypress/support/step_definitions. If you want to put them somewhere please use cosmiconfig format. For example, add to your package.json :

  "cypress-cucumber-preprocessor": {
    "step_definitions": "cypress/support/step_definitions/"
  }
```

Again - cypress.json is CYPRESS configuration, not our plugin configuration. We don't have control over it, and Cypress team was unfortunately quiet about them allowing us put any custom keys there. As far as I know they don't have any policy about having plugins putting their own configs on top of theirs - feel free to reach out to them, and if you reach an agreement, we are happy to make changes.
But, the statement that 'the 'step_definitions' will only be read from package.json' is actually not even true. We use cosmiconfig, as stated in the documentation. :) 


There is multiple things wrong with the repo you provided.

First, you define the step definitions inside  your cypress config, even though you know that's incorrect.

Second, you don't have all the steps defined "I should see "Hello World"" is missing

Third, you are requiring functions from cucumber, not from our package. that won't work. Try not requiring thos at all and just using them (they are globally available, like cy )

Fourth: 
```javascript
  on('file:preprocessor', webpack({
    webpackOptions: require('@vue/cli-service/webpack.config'),
    watchOptions: {}
  }))
  on('file:preprocessor', cucumber())

```

this is incorrect - you set up two handlers to the same event, it should be one.  try this https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/18#issuecomment-384245388 

(and if it helps - please create a PR with an update to the doCs)

There might be more, but those were jumping at me right away. 

I also don't get the error you displayed here.
In the future, when you make a reproduction for any issue, for any package/library, please, please, please - make a list of steps to get to the reproduction point. I'm not getting paid to help you - why do you make me jump through hoops to figure out how to get to the error you see? :) 

So far, I'm closing this as this is not really an issue with the library so far, but a problem with configuration. Once you fix all those problems and create a proper repro, please reopen or create a new one.

Thanks!

**Closed by lgandecki** 2018-10-06 04:59 UTC

**Comment by TobiG77** [comment] 2018-10-06 06:28
Hi,

Thanks for providing some background around why the config can only be configured that way. I was lacking that context and had obviously some wrong assumptions / expectations - despite reading the documentation. 

The comment was indeed the right solution. I've pushed the changes in the repository for use of cypress and cucumber - without the e2e-express vue-cli plugin - which resolve the situation, so others can find it. 

I'll create a doc PR once I have the other configuration scenario confirmed as operational.

**Comment by lgandecki** [comment] 2018-10-06 06:35
Great! Thanks for the update! And if you can indeed share the experience you got with a PR to the docs that would be fantastic!

**Comment by stevengunneweg** [comment] 2021-08-20 06:51
I just ran into the same error, for me it was resolved by importing the "Given, Then, When" from `cypress-cucumber-preprocessor/steps instead` of the `cucumber` package.

My issue was not related to Vue but since this was the first hit on Google I thought it would be worth mentioning.
