### ISSUE TITLE
Working on calling step from other step, need function 'resolveStepDefinition' be exported in steps.js

### ISSUE THREAD

**Issue by Ceci-chen** [TheBrainFamily/cypress-cucumber-preprocessor#502] opened 2021-01-28 08:24 UTC
My team is using cypress-cucumber-preprocessor, it's so great and helpful. In our old project (selenium+cucumber.ruby), we relied on 'step' function to call step from other step, now we're migrating test, people would love to have that function with cypress-cucumber;
The issue is we can't import/require function 'resolveStepDefinition' in the framework, because it's not exported in /node_modules/cypress-cucumber-preprocessor/steps.js.

### Current behavior
When we import 'cypress-cucumber-preprocessor/steps', we only get 
 Then,
  And,
  But,
  Given,
  When,
  Before,
  After,
  defineParameterType,
  defineStep,

### Desired behavior
Hoping we can have 'resolveStepDefinition' exported in steps.js, I guess it shouldn't be too much work. We could move whole cypress-cucumber-preprocessor folder to /plugins of cypress, but we wouldn't want to miss any new update of this repo in the future. So, can someone help? Thanks very much!

### Versions

* **Cypress version**: 5.6.0
* **Preprocessor version**: 4.0.0
* **Node version**: 12.13.0

**Comment by badeball** [comment] 2021-01-28 08:52
Duplicate of https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/170.

**Closed by badeball** 2021-01-28 08:52 UTC

**Comment by lgandecki** [comment] 2021-01-28 09:56
So looks like badeball has a workaround for you :) Let us know if it works for you, preferably in that other thread. 
Also, thanks for the nice words!

**Comment by edmodo-CeciliaChen** [comment] 2021-01-29 03:22
I saw the workaround in #170, tried that and worked, thanks for your help!!
