### ISSUE TITLE
Rule keyword support for cucumber

### ISSUE THREAD

**Issue by asankasira** [TheBrainFamily/cypress-cucumber-preprocessor#495] opened 2021-01-18 02:31 UTC
I have read that **Rule** keyword has been part of Gherkin since v6. Rule is used to group together several scenarios that belong to this business rule and it could contain one or more scenarios that illustrate the particular rule. 

### Current behavior

I am using the latest version (4.0.0)  of cypress-cucumber-processor and seems like Rule keyword is not supported. (might be due to the associated cucumber js version is 4.2.1? )

### Desired behavior

It would be nice to have the **Rule** keyword support, since we can group scenarios and even provide a different **Background** section within the Rule

### Versions

* **Cypress version**: 6.2.1
* **Preprocessor version**:  4.0.0
* **Node version**: 14.15.3

**Comment by badeball** [comment] 2021-01-18 08:10
Duplicate of https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/143.

**Closed by badeball** 2021-01-18 08:10 UTC

**Comment by lgandecki** [comment] 2021-01-18 08:17
I think it's worth to add though that with merging https://github.com/badeball/cypress-cucumber-preprocessor in here Rule keyword will be available. We might not be far from doing so :)

**Comment by asankasira** [comment] 2021-01-18 09:57
Thanks @lgandecki. Please let us know once you have merged it to the main path. Could not use the forked version as some important aspects are missing like "All.features" support

**Comment by raymundosaraiva** [comment] 2021-06-01 16:56
Hey @lgandecki , any expected date for merging this new cool feature?
