### ISSUE TITLE
commonPath property doesn't work

### ISSUE THREAD

**Issue by amitguptagwl** [TheBrainFamily/cypress-cucumber-preprocessor#213] opened 2019-08-22 09:42 UTC
I want to change the name of common folder to steps folder;

```json
"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "commonPath" : "cypress/integration/steps",
  }
```
It doesn't work

**Comment by lgandecki** [comment] 2019-08-22 09:52
Please make a small reproduction and push to github

**Comment by amitguptagwl** [comment] 2019-08-22 12:32
ok.. let me update

**Comment by sagorla** [comment] 2019-09-26 21:05
@lgandecki 

const commonPath =
      loaded.config.commonPath || `${stepDefinitionPath()}/common/`;

based on above current logic commonPath is directly referring to "loaded.config.commonPath" if commonPath is configured in package.json. In this case (based on @amitguptagwl configuration) "loaded.config.commonPath" value will be "cypress/integration/steps". So directly we are trying get common .js files from "cypress/integration/steps" without giving appRoot folder hence cypress is not able to find the valid path.

If get commonPath under appRoot folder as mentioned below, working fine.

const appRoot = process.cwd();
const commonPath =
    `${appRoot}/${loaded.config.commonPath}` || `${stepDefinitionPath()}/common/`;

**Comment by amadridlar** [comment] 2019-11-28 09:58
I have the same issue, working on the example project https://github.com/TheBrainFamily/cypress-cucumber-example.

I have modified the name of the common steps folder to 'common-steps' and the configuration of  ```cypress-cucumber-preprocessor``` in the package.json like this:
```
"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "commonPath": "cypress/integration/common-steps"
  }
```
When I execute the test, this is the error I get:

```Error: Cannot find module 'cypress/integration/common-steps/I_see_STRING_in_the_title.js' from 'C:\Users\user\workspace\cypress-cucumber-example\cypress\integration\socialNetworks'```

If I let the default folder name and the default value on that property, it works, but changing the name of the common steps folder and modifying the property results on that error.

**Comment by iambacon** [comment] 2020-03-04 04:08
I am getting the same issue and can reproduce with the same steps as @sagorla and @amadridlar. Would be great to be able to use this config setting.

**Comment by fermeaux** [comment] 2020-04-02 10:21
Same issue here. Relative path didn't work but the whole path worked for the `stepDefinitions`.
My case not working :
```
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "stepDefinitions": "./e2e/src/integration"
  }
```
My case working :
```
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "stepDefinitions": "D:/projects/myproject/e2e/src/integration"
  }
```
I think you don't manage relative path.

**Comment by kkuriata** [comment] 2020-04-05 18:56
Anyone is going to fix that issue? It is impossible to use this plugin with non-default folder structure (especially when you use monorepo like Nx).

**Comment by flanzana** [comment] 2020-06-02 12:45
I have the same issue (Cannot share original repo because it is private in GitLab, but I reproduced it in the same example: https://github.com/flanzana/cypress-cucumber-example/tree/master/cypress/features)

For me common steps work with this set up:
```
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "commonPath": ".cypress/features/common",
    "stepDefinitions": "./cypress/features",
}
```

BUT with having `nonGlobalStepDefinitions` `false`, a non-common step with the same sentence but different implementation in different features are overwritten - it is breaking some of the features - for example, step `Then I am very happy` is in Facebook and Google, but when you run Google.feature, it will look for Facebook in title, not Google. 😢 

I tried to make it work with `true`, but nothing fixes it so for, common steps are not found.

🙏 🙏

**Comment by LPCmedia** [comment] 2020-06-11 07:34
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/236

should handle this issue.

**Comment by lgandecki** [comment] 2020-06-23 16:56
Is this still an issue? or as @LPCmedia suggests, we can close this one?

**Comment by iambacon** [comment] 2020-06-24 04:15
@lgandecki This is the same issue as #236 so I think it can be closed

**Comment by lgandecki** [comment] 2020-06-24 07:41
Thanks! Please create a new one if something is still not right.

**Closed by lgandecki** 2020-06-24 07:41 UTC
