### ISSUE TITLE
Is it possible to tag the Examples in Scenario Outline

### ISSUE THREAD

**Issue by rameshbestha** [TheBrainFamily/cypress-cucumber-preprocessor#452] opened 2020-10-05 03:10 UTC
If my feature file is like below
Scenario Outline: ...
        Given I login with "<userid>" and "<password>"
        And ......        
        Then ......
        
	@sit
        Examples:
            |userid            | password  |
            |sittest1@test.com | test      |
            
        @uat
        Examples:
            |userid            | password |
            |uattest1@test.com | test     |

Can I run the scenarios like this
cypress run  TAGS=@sit and the test pick only @sit Examples
and if I run like this 
cypress run TAGS=@uat and the test pick only @uat Examples

**Comment by badeball** [comment] 2020-10-05 09:09
This is a duplicate of https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/196. Closing to keep everything in one place.

**Closed by badeball** 2020-10-05 09:09 UTC
