### ISSUE TITLE
Tests take very long to start

### ISSUE THREAD

**Issue by mwanago** [TheBrainFamily/cypress-cucumber-preprocessor#295] opened 2020-01-02 12:00 UTC
Hello!
I'm struggling with the performance of the test with the use of cypress-cucumber-preprocessor. It hangs on this screen in the browser:

![image](https://user-images.githubusercontent.com/15181215/71666111-d9f3d480-2d5f-11ea-9e46-42993d4ed45e.png)

In the node terminal I can see such potential causes:

``` GET /__/ 200 25.117 ms - -
GET /__cypress/runner/cypress_runner.css 200 5.750 ms - -
GET /__cypress/runner/cypress_runner.js 200 4.877 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2 200 1.103 ms - 77160
GET /__cypress/iframes/integration/FeatureName.feature 200 2.750 ms - 753
GET /__cypress/tests?p=cypress%5Csupport%5Cindex.js-310 200 37241.251 ms - -
GET /__cypress/tests?p=cypress%5Cintegration%5CFeatureName.feature-891 200 40345.918 ms - -
```
As you can see, there are some files that take a very long time to load properly.

This line seems to be problematic:
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/lib/index.js#L46

Without this await here everything works quite fast. Do you have a clue what might be the issue here? I'm using Windows 10 with Node v12.13.1.

**Comment by lgandecki** [comment] 2020-01-02 15:00
Hello. Thanks for the submitting issue and sorry for the problems! Looks like I have to revert that commit, will work on this and some of the stale issues next week. For now it should be fine for you to go a few versions back. 1.18.0 should do the trick

**Comment by mwanago** [comment] 2020-01-03 08:13
@lgandecki Thank you for a quick response. I had to roll back to 1.17.0 for this line to disappear.
Thanks for all the hard work!

**Comment by mwanago** [comment] 2020-01-03 08:58
@lgandecki 
There are quite a few issues in the `ps-node` library indicating that there are performance issues on Windows
https://github.com/neekey/ps/issues

**Comment by pravynandas** [comment] 2020-01-06 16:17
I'm using 1.16.2 which appears to be stable than 1.17.0 but I too notice a noticeable performance delay when starting first feature file after cypress started (+40 seconds) and upon next run (+10 seconds).. Following a subset of log from (set DEBUG=cypress*&&npm run ..) command where I notice something suspicious... Any clues? @lgandecki @mwanago 

**Note:** If i run a standard *.spec.js test script, it starts almost instantaneously.

cypress:server:events sending ipc data { type: 'get:project:status', data: { id: 0.35663456046380393, data: { path: 'C:\\Users\\<user>\\Repo\\<project_base_folder>\\ui', state: 'VALID'
 } } } +16ms
  cypress:browserify finished bundling: C:\Users\<user>\AppData\Roaming\Cypress\cy\production\projects\ui-417ea8e8657c3973acf0ad6fe5826428\bundles\cypress\integration\Features\re
lease.feature **+15s**
  cypress:server:plugins promise resolved for id 'inv76' with value C:\Users\<user>\AppData\Roaming\Cypress\cy\production\projects\ui-417ea8e8657c3973acf0ad6fe5826428\bundles\cyp
ress\integration\Features\release.feature **+15s**
  cypress:server:controllers:spec sending spec { filePath: 'C:\\Users\\<user>\\AppData\\Roaming\\Cypress\\cy\\production\\projects\\ui-417ea8e8657c3973acf0ad6fe5826428\\bundles\\
cypress\\integration\\Features\\release.feature' } **+15s**
GET /__cypress/tests?p=cypress%5Cintegration%5CFeatures%5Crelease.feature-811 200 15046.796 ms - -
  cypress:server:browsers:electron console message: { column: 32, level: 'log', line: 178269, source: 'console-api', text: 'console.clear', url: 'http://localhost:8080/__cypress/r
unner/cypress_runner.js' } **+16s**
  cypress:server:socket automation:request get:cookies { domain: 'localhost' } **+16s**
  cypress:server:cookies getting:cookies { domain: 'localhost' } **+46s**
  cypress:server:browsers:electron debugger: sending Network.getAllCookies with params undefined +64ms

**Comment by lgandecki** [comment] 2020-01-06 16:24
the differences between 1.16.2 and 1.17.0 are as you can check here: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/compare/v1.16.2..v1.17.0 , so that shouldn't matter.

Looks like the test gets stuck on cypress:server:cookies and socket commands (one minute togeter), are you sure your .spec.js also run these steps?

**Comment by pravynandas** [comment] 2020-01-06 19:10
Here is the log extract when I run a spec.js file (fresh start with cypress:open command)... The delay about 10seconds on a fresh start and almost instant when a re-run of the same spec.js file. Let me know if any additional information needed to debug. Thanks in advance.

cypress:server:controllers:spec sending spec { filePath: 'C:\\Users\\<user>\\AppData\\Roaming\\Cypress\\cy\\production\\projects\\ui-417ea8e8657c3973acf0ad6fe5826428\\bundles\
\cypress\\integration\\02.release.spec.js' } **+4s**
GET /__cypress/tests?p=cypress%5Cintegration%5C02.release.spec.js-330 200 4114.461 ms - -
  cypress:server:events got request for event: get:project:status, { path: 'C:\\Users\\<user>\\Repo\\<project_base_folder>\\ui' } **+7s**
  cypress:server:project get project status for client id undefined at path C:\Users\<user>\Repo\<project_base_folder>\ui **+10s**
  cypress:server:project no project id +1ms
  cypress:server:events sending ipc data { type: 'get:project:status', data: { id: 0.48950603809433946, data: { path: 'C:\\Users\\<user>\\Repo\\<project_base_folder>\\ui', state: 'VALID
' } } } +18ms
  cypress:browserify finished bundling: C:\Users\<user>\AppData\Roaming\Cypress\cy\production\projects\ui-417ea8e8657c3973acf0ad6fe5826428\bundles\cypress\support\index.js **+6s**
  cypress:server:plugins promise resolved for id 'inv3' with value C:\Users\<user>\AppData\Roaming\Cypress\cy\production\projects\ui-417ea8e8657c3973acf0ad6fe5826428\bundles\cyp
ress\support\index.js **+6s**
  cypress:server:controllers:spec sending spec { filePath: 'C:\\Users\\<user>\\AppData\\Roaming\\Cypress\\cy\\production\\projects\\ui-417ea8e8657c3973acf0ad6fe5826428\\bundles\
\cypress\\support\\index.js' } **+6s**
GET /__cypress/tests?p=cypress%5Csupport%5Cindex.js-388 200 10253.226 ms - -
  cypress:server:socket automation:request get:cookies { domain: 'localhost' } **+11s**
  cypress:server:cookies getting:cookies { domain: 'localhost' } +0ms
  cypress:server:browsers:electron debugger: sending Network.getAllCookies with params undefined **+11s**

**Comment by pravynandas** [comment] 2020-01-06 21:42
Not sure if this adds any value to debug, but I see below log repeated every 10s even when there are no tests running actively. Also it seems the id in ipc data element is not fetched correctly (id undefined)..

cypress:server:events sending ipc data { type: 'get:project:status', data: { id: 0.5012873103360875, data: { path: 'C:\\Users\\<user>\\Repo\\<project>\\ui', state: 'VALID' } } } +1ms
  cypress:server:events got request for event: get:project:status, { path: 'C:\\Users\\<user>\\Repo\\<project>\\ui' } **+10s**
  cypress:server:project get project status for **client id undefined** at path C:\Users\<user>\Repo\<project>\ui +10s
  cypress:server:project no project id +0ms

**Comment by greenwest** [comment] 2020-01-13 12:00
Hi! I'm experiencing the same as the author does. Had written a simple test to open a google page and take its screenshot and it for me it takes:
 around 16 seconds to complete on 1.17.0
 around 80 seconds to complete on 1.18.0
 4 seconds if I'm not using cypress-cucumber-preprocessor and doing this in a regular cypress way

I have a shared step def placed in a file under a common folder
and 
`{
  "testFiles": "**/*.{feature,features}",
  "ignoreTestFiles": "*.js"
}`
in my cypress.json

Is there any fix coming in a observable future?
Please ping me if you need any additional information from my side.
Thanks! =)

**Comment by lgandecki** [comment] 2020-01-13 19:09
Guys, please try with version 2.0.0  - I hope it's faster. @greenwest if you could post your time with 2.0.0 that would be great as well.

**Comment by greenwest** [comment] 2020-01-14 15:07
@lgandecki Nice work, thank you! It's totally better with 2.0.0. Now I'm getting around 4-5 seconds when I'm running it using command line. On the first attempt to run it through the cypress GUI it takes around 10 sec but after I hit re-run it drops to like 2 or 3 seconds.

**Comment by pravynandas** [comment] 2020-01-14 17:01
Hi @lgandecki thanks for the great work!!. I was excited to run on the latest version but unfortunately the test is breaking for version 2.0.0. Not sure if some configuration changes would fix it but except the version upgrade (and adding two elements to the configuration in package.json), I did not do any changes but it fails to run. 

Please review and suggest. Also tried changing feature (and folder) name from 01.Navigation to 01Navigation without any luck.

### Folder structure:
cypress
|-- integration
......|-- common
.............|-- common-steps.js
......|-- 01.Navigation
.............|-- visit.steps.js
......|-- 01.Navigation.feature


### plugins/index.js

```
module.exports = (on, config) => {

  on('file:preprocessor', cucumber());

  on('task', (...));

  on('after:screenshot', (...));

}
```
	
### cypress-cucumber-preprocessor@1.16.2 (SUCCESS)

#### package.json
```
{
	...
	"cypress": "3.7.0",
	"cypress-cucumber-preprocessor": "1.16.2",
	...
	"cypress-cucumber-preprocessor": {
		"nonGlobalStepDefinitions": true,
		"cucumberJson": {
			"generate": true,
			"outputFolder": "cypress/cucumber-json",
			"filePrefix": "",
			"fileSuffix": ".cucumber"
		}
	}
}
```
```
  cypress:cucumber cucumber.json {"generate":true,"outputFolder":"cypress/cucumber-json","filePrefix":"","fileSuffix":".cucumber"} +0ms
  cypress:server:plugins:child execute plugin event: file:preprocessor ({ eventId: 2, invocationId: 'inv2' }) +505ms
  cypress:browserify received user options: { browserifyOptions: { extensions: [ '.js', '.jsx', '.coffee' ], transform: [ [Function: transform], [Array], [Array] ], plugin: [] }, watchifyOptions: { ignoreWatch: [ '**/.git/**', '**/.nyc_output/**', '**/.sass-cache/**', '**/bower_components/**', '**/coverage/**', '**/node_modules/**' ] } } +449ms
  cypress:browserify get: C:\Users\<user>\Repo\<project>\ui\cypress\support\index.js +1ms
  cypress:browserify input: C:\Users\<user>\Repo\<project>\ui\cypress\support\index.js +0ms
  cypress:browserify output: C:\Users\<user>\AppData\Roaming\Cypress\cy\production\projects\ui-417ea8e8657c3973acf0ad6fe5826428\bundles\cypress\support\index.js +0ms
  cypress:browserify browserifyOptions: { extensions: [ '.js', '.jsx', '.coffee' ], transform: [ [Function: transform], [ 'C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\coffeeify\\index.js', [Object] ], [ 'C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\babelify\\index.js', [Object] ] ], plugin: [], cache: {}, packageCache: {}, debug: true, entries: [ 'C:\\Users\\<user>\\Repo\\<project>\\ui\\cypress\\support\\index.js' ] } +0ms
  cypress:browserify making bundle C:\Users\<user>\AppData\Roaming\Cypress\cy\production\projects\ui-417ea8e8657c3973acf0ad6fe5826428\bundles\cypress\support\index.js +7ms
  cypress:browserify **finished bundling**: C:\Users\<user>\AppData\Roaming\Cypress\cy\production\projects\ui-417ea8e8657c3973acf0ad6fe5826428\bundles\cypress\support\index.js +33s
  cypress:server:plugins promise resolved for id 'inv2' with value C:\Users\<user>\AppData\Roaming\Cypress\cy\production\projects\ui-417ea8e8657c3973acf0ad6fe5826428\bundles\cypress\support\index.js +0ms
```
  
### cypress-cucumber-preprocessor@2.0.0 (FAILURE)
  
  
####
```
{
	...
	"cypress": "3.7.0",
	"cypress-cucumber-preprocessor": "^2.0.0",
	...
	"cypress-cucumber-preprocessor": {
		"nonGlobalStepDefinitions": true,
		"stepDefinitions": "cypress/integration",     <-- added newly
		"commonPath": "cypress/integration/common", <-- added newly
		"cucumberJson": {
			"generate": true,
			"outputFolder": "cypress/cucumber-json",
			"filePrefix": "",
			"fileSuffix": ".cucumber"
		}
	}
}
```

```
    cypress:cucumber cucumber.json {"generate":true,"outputFolder":"cypress/cucumber-json","filePrefix":"","fileSuffix":".cucumber"} +0ms
  cypress:browserify **errored bundling**: C:\Users\<user>\AppData\Roaming\Cypress\cy\production\projects\ui-417ea8e8657c3973acf0ad6fe5826428\bundles\cypress\integration\01.Navigation.feature { Error: Parsing file C:\Users\<user>\Repo\<project>\ui\cypress\integration\01.Navigation.feature: Bad character escape sequence (14:50)
    at Deps.parseDeps (C:\Users\<user>\Repo\<project>\ui\node_modules\module-deps\index.js:510:15)
    at getDeps (C:\Users\<user>\Repo\<project>\ui\node_modules\module-deps\index.js:438:44)
    at C:\Users\<user>\Repo\<project>\ui\node_modules\module-deps\index.js:421:38
    at ConcatStream.<anonymous> (C:\Users\<user>\Repo\<project>\ui\node_modules\concat-stream\index.js:37:43)
    at ConcatStream.emit (events.js:199:15)
    at finishMaybe (C:\Users\<user>\Repo\<project>\ui\node_modules\readable-stream\lib\_stream_writable.js:630:14)
    at endWritable (C:\Users\<user>\Repo\<project>\ui\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at ConcatStream.Writable.end (C:\Users\<user>\Repo\<project>\ui\node_modules\readable-stream\lib\_stream_writable.js:594:41)
    at DuplexWrapper.onend (C:\Users\<user>\Repo\<project>\ui\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:282:20)
    at DuplexWrapper.emit (events.js:199:15)
    at endReadableNT (C:\Users\<user>\Repo\<project>\ui\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

  stream:
   Labeled {
     _readableState:
      ReadableState {
        objectMode: true,
        highWaterMark: 16,
        buffer: BufferList { length: 0 },
        length: 0,
        pipes: [Labeled],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     _events:
      [Object: null prototype] {
        end: [Array],
        error: [Function],
        data: [Function: ondata],
        _mutate: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: true,
        highWaterMark: 16,
        finalCalled: false,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [CorkedRequest] },
     writable: false,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Deps] ],
     length: 1,
     label: 'deps' },
  filePath:
   'C:\\Users\\<user>\\Repo\\<project>\\ui\\cypress\\integration\\01.Navigation.feature',
  originalStack:
   'Error: Parsing file C:\\Users\\<user>\\Repo\\<project>\\ui\\cypress\\integration\\01.Navigation.feature: Bad character escape sequence (14:50)\n    at Deps.parseDeps (C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\module-deps\\index.js:510:15)\n    at getDeps (C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\module-deps\\index.js:438:44)\n
  at C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\module-deps\\index.js:421:38\n    at ConcatStream.<anonymous> (C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\concat-stream\\index.js:37:43)\n    at ConcatStream.emit (events.js:199:15)\n    at finishMaybe (C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\readable-stream\\lib\\_stream_writable.js:630:14)\n    at endWritable (C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\readable-stream\\lib\\_stream_writable.js:638:3)\n    at ConcatStream.Writable.end (C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\readable-stream\\lib\\_stream_writable.js:594:41)\n    at DuplexWrapper.onend (C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\readable-stream\\lib\\_stream_readable.js:577:10)\n    at Object.onceWrapper (events.js:282:20)\n    at DuplexWrapper.emit (events.js:199:15)\n    at endReadableNT (C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\readable-stream\\lib\\_stream_readable.js:1010:12)\n    at processTicksAndRejections (internal/process/task_queues.js:81:17)\n' } +508ms
  cypress:server:plugins promise rejected for id inv1 ':' Error: Parsing file C:\Users\<user>\Repo\<project>\ui\cypress\integration\01.Navigation.feature: Bad character escape sequence (14:50)
    at Deps.parseDeps (C:\Users\<user>\Repo\<project>\ui\node_modules\module-deps\index.js:510:15)
    at getDeps (C:\Users\<user>\Repo\<project>\ui\node_modules\module-deps\index.js:438:44)
    at C:\Users\<user>\Repo\<project>\ui\node_modules\module-deps\index.js:421:38
    at ConcatStream.<anonymous> (C:\Users\<user>\Repo\<project>\ui\node_modules\concat-stream\index.js:37:43)
    at ConcatStream.emit (events.js:199:15)
    at finishMaybe (C:\Users\<user>\Repo\<project>\ui\node_modules\readable-stream\lib\_stream_writable.js:630:14)
    at endWritable (C:\Users\<user>\Repo\<project>\ui\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at ConcatStream.Writable.end (C:\Users\<user>\Repo\<project>\ui\node_modules\readable-stream\lib\_stream_writable.js:594:41)
    at DuplexWrapper.onend (C:\Users\<user>\Repo\<project>\ui\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:282:20)
    at DuplexWrapper.emit (events.js:199:15)
    at endReadableNT (C:\Users\<user>\Repo\<project>\ui\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
 +0ms

Oops...we found an error preparing this test file:

  cypress\integration\01.Navigation.feature

The error was:

**Error: Parsing file C:\Users\<user>\Repo\<project>\ui\cypress\integration\01.Navigation.feature: Bad character escape sequence (14:50)**


This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

**Comment by lgandecki** [comment] 2020-01-14 17:07
@pravynandas  Can you please try 2.0.1?

**Comment by lgandecki** [comment] 2020-01-14 17:09
@greenwest this looks like you might be missing baseUrl in the cypress configuration, can you verify?

**Comment by greenwest** [comment] 2020-01-14 17:22
@lgandecki Yes, you're totally right. I forgot to add it. Thanks!

**Comment by pravynandas** [comment] 2020-01-14 19:23
Hi @lgandecki with v2.0.1 I think the previously reported error (Bad escape character sequence) is gone. But getting a different error which also seemingly appearing from 1.19.0. See the [Issue ](https://github.com/TheBrainFamily/cypress-cucumber-example/issues/14) on our example.

```
cypress:cucumber cucumber.json {"generate":true,"outputFolder":"cypress/cucumber-json","filePrefix":"","fileSuffix":".cucumber"} +0ms
  cypress:server:plugins:child execute plugin event: file:preprocessor ({ eventId: 2, invocationId: 'inv2' }) +1s
  cypress:browserify received user options: { browserifyOptions: { extensions: [ '.js', '.jsx', '.coffee' ], transform: [ [Function: transform], [Array], [Array] ], plugin: [] }, watchifyOptions: { ignoreWatch: [ '**/.git/**', '**/.nyc_output/**', '**/.sass-cache/**', '**/bower_components/**', '**/coverage/**', '**/node_modules/**' ] } } +1s
  cypress:browserify get: C:\Users\<user>\Repo\<project>\ui\cypress\support\index.js +0ms
  cypress:browserify input: C:\Users\<user>\Repo\<project>\ui\cypress\support\index.js +0ms
  cypress:browserify output: C:\Users\<user>\AppData\Roaming\Cypress\cy\production\projects\ui-417ea8e8657c3973acf0ad6fe5826428\bundles\cypress\support\index.js +0ms  cypress:browserify browserifyOptions: { extensions: [ '.js', '.jsx', '.coffee' ], transform: [ [Function: transform], [ 'C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\coffeeify\\index.js', [Object] ], [ 'C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\babelify\\index.js', [Object] ] ], plugin: [], cache:
{}, packageCache: {}, debug: true, entries: [ 'C:\\Users\\<user>\\Repo\\<project>\\ui\\cypress\\support\\index.js' ] } +0ms
  cypress:browserify making bundle C:\Users\<user>\AppData\Roaming\Cypress\cy\production\projects\ui-417ea8e8657c3973acf0ad6fe5826428\bundles\cypress\support\index.js +6ms
  cypress:browserify errored bundling: C:\Users\<user>\AppData\Roaming\Cypress\cy\production\projects\ui-417ea8e8657c3973acf0ad6fe5826428\bundles\cypress\integration\01Navigation.feature { Error: Cannot find module 'cypress/integration/common/common.steps.js' from 'C:\Users\<user>\Repo\<project>\ui\cypress\integration'
    at C:\Users\<user>\Repo\<project>\ui\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\<user>\Repo\<project>\ui\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\<user>\Repo\<project>\ui\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\<user>\Repo\<project>\ui\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\<user>\Repo\<project>\ui\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\<user>\Repo\<project>\ui\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at callback (C:\Users\<user>\AppData\Local\Cypress\Cache\3.7.0\Cypress\resources\app\packages\server\node_modules\graceful-fs\polyfills.js:295:20)
    at FSReqCallback.oncomplete (fs.js:163:21)

  stream:
   Labeled {
     _readableState:
      ReadableState {
        objectMode: true,
        highWaterMark: 16,
        buffer: BufferList { length: 0 },
        length: 0,
        pipes: [Labeled],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     _events:
      [Object: null prototype] {
        end: [Array],
        error: [Function],
        data: [Function: ondata],
        _mutate: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: true,
        highWaterMark: 16,
        finalCalled: false,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [CorkedRequest] },
     writable: false,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Deps] ],
     length: 1,
     label: 'deps' },
  filePath:
   'C:\\Users\\<user>\\Repo\\<project>\\ui\\cypress\\integration\\01Navigation.feature',
  originalStack:
   "Error: Cannot find module 'cypress/integration/common/common.steps.js' from 'C:\\Users\\<user>\\Repo\\<project>\\ui\\cypress\\integration'\n    at C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\browser-resolve\\node_modules\\resolve\\lib\\async.js:46:17\n    at process (C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\browser-resolve\\node_modules\\resolve\\lib\\async.js:173:43)\n    at ondir (C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\browser-resolve\\node_modules\\resolve\\lib\\async.js:188:17)\n    at load (C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\browser-resolve\\node_modules\\resolve\\lib\\async.js:69:43)\n    at onex (C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\browser-resolve\\node_modules\\resolve\\lib\\async.js:92:31)\n    at C:\\Users\\<user>\\Repo\\<project>\\ui\\node_modules\\browser-resolve\\node_modules\\resolve\\lib\\async.js:22:47\n    at callback (C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\3.7.0\\Cypress\\resources\\app\\packages\\server\\node_modules\\graceful-fs\\polyfills.js:295:20)\n    at FSReqCallback.oncomplete (fs.js:163:21)\n" } +27s
  cypress:server:plugins promise rejected for id inv1 ':' Error: Cannot find module 'cypress/integration/common/common.steps.js' from 'C:\Users\<user>\Repo\<project>\ui\cypress\integration'
    at C:\Users\<user>\Repo\<project>\ui\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\<user>\Repo\<project>\ui\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\<user>\Repo\<project>\ui\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\<user>\Repo\<project>\ui\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\<user>\Repo\<project>\ui\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\<user>\Repo\<project>\ui\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at callback (C:\Users\<user>\AppData\Local\Cypress\Cache\3.7.0\Cypress\resources\app\packages\server\node_modules\graceful-fs\polyfills.js:295:20)
    at FSReqCallback.oncomplete (fs.js:163:21)
 +0ms

Oops...we found an error preparing this test file:

  cypress\integration\01Navigation.feature

The error was:

Error: Cannot find module 'cypress/integration/common/common.steps.js' from 'C:\Users\<user>\Repo\<project>\ui\cypress\integration'


This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

**Comment by lgandecki** [comment] 2020-01-14 20:13
Can you open a new issue and create a reproduction? I consider this issue fixed now. If there are more - let's chase them

**Closed by lgandecki** 2020-01-14 20:13 UTC

**Comment by pravynandas** [comment] 2020-01-30 02:13
Thanks. Perhaps as mentioned [here ](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/310#issuecomment-577232854) the (new) issue fixed by below simple configuration.

`"cypress-cucumber-preprocessor": { "nonGlobalStepDefinitions": true, }`

Thanks for all the great work. This plugin is an integral part of my daily job.
